"""Reframe paper/ejp/qsol_cqed_ejp.tex for the European Journal of Physics
(teaching audience).  Run after make_ejp_iopjournal.py.  Physics content and
numbers are unchanged; the abstract, introduction, Sec. 2.1, Sec. 6 and the
conclusions are rewritten, Sec. 2.9 (Mollow triplet, figure no longer shown) is
removed, and a new Sec. 7 'Using this material in teaching' is added."""
import re, pathlib, sys

P = pathlib.Path('/Users/alanknguyen/Documents/qsol_cqed/paper/ejp/qsol_cqed_ejp.tex')
s = P.read_text()

def span(start, end):
    i = s.index(start); j = s.index(end, i)
    assert s.count(start) == 1, start
    return i, j

def replace_span(start, end, new):
    global s
    i, j = span(start, end); s = s[:i] + new + s[j:]

# ---------------------------------------------------------------- abstract
ABSTRACT = r"""The Jaynes--Cummings (JC) model is the standard first encounter with quantized light--matter interaction, yet most courses stop at the collapse and revival of Rabi oscillations and leave three of its most instructive lessons untaught: what the cavity field looks like in phase space while the oscillations are collapsed, how the atom--field entanglement evolves through a collapse--revival cycle, and how quickly cavity loss erases the non-classical features. We present a self-contained computational treatment of these questions for advanced undergraduate and beginning graduate students, in which every figure is generated by a short QuTiP script that the reader can run and modify. Starting from the dipole Hamiltonian we derive the JC model, its dressed states, and the collapse and revival times $t_c = O(1/g)$ and $t_r = 2\pi\sqrt{\bar{n}}/g$, then solve the Lindblad master equation for an initially excited atom and a coherent field with $\bar{n} = 10$. Three results organize the discussion. (i) At half the revival time the field is a Schr\"{o}dinger cat state with Wigner negativity $\delta = 0.85$, purity 0.96 and fidelity 0.78 to a two-component cat, and the atom has disentangled from it (reduced entropy $S \approx 0.14$~bit); during the preceding collapse the atom and field are instead maximally entangled and the reduced field is a two-branch mixture. (ii) Among coherent, thermal, squeezed and Fock initial fields, this half-revival disentanglement occurs only for the coherent field, and a thermal field saturates the reduced entropy at one bit while its logarithmic negativity stays near 0.2, showing why the reduced entropy measures entanglement only for pure global states. (iii) A cavity decay rate of $\kappa/g = 0.02$ removes over 80\% of the Wigner negativity. We close with exercises built on the code and a mapping of the results onto microwave and circuit-QED parameters."""
i, j = span('\\begin{abstract}\n', '\n\\end{abstract}')
s = s[:i] + '\\begin{abstract}\n' + ABSTRACT + s[j:]

# ---------------------------------------------------------------- keywords
old_kw = '\\keywords{quantum optics, Jaynes--Cummings model, Wigner function, entanglement entropy, cavity QED, Schr\\"{o}dinger cat state, decoherence}'
assert s.count(old_kw) == 1
s = s.replace(old_kw, '\\keywords{Jaynes--Cummings model, Wigner function, Schr\\"{o}dinger cat state, entanglement entropy, decoherence, cavity QED, computational physics education, QuTiP}')

# ---------------------------------------------------------------- introduction (paragraphs 3-4)
INTRO = r"""While the JC model appears in every quantum-optics course, most presentations stop at the collapse and revival of the atomic inversion and leave three of its most instructive lessons untaught: what the cavity field looks like in phase space while the oscillations are collapsed, how the atom--field entanglement evolves through a collapse--revival cycle, and how quickly cavity loss erases the non-classical features. The lessons are not new to the research literature. Eberly \textit{et al.}~\cite{eberly1980} explained the collapse and revival, Gea-Banacloche~\cite{gea-banacloche1990, gea-banacloche1991} showed that the atom and field disentangle at half the revival time and leave the field in a Schr\"{o}dinger cat state, and Phoenix and Knight~\cite{phoenix1988, phoenix1991} traced the entanglement entropy through the cycle. They are, however, easy to misread. The cat state and the peak of the entanglement both occur while the inversion is collapsed, and it is tempting to identify one with the other; separating them requires watching the Wigner function, the field purity and the atomic entropy at the same time, which is exactly what a computational treatment makes cheap.

This paper is written for advanced undergraduate and beginning graduate students, and for instructors of quantum-optics or computational-physics courses. It assumes second quantization of a single mode, density matrices and the partial trace, and a first exposure to master equations; Section~\ref{sec:theory} supplies a self-contained derivation of the rest, and readers who know the JC model can proceed directly to Section~\ref{sec:methods}. Every figure is produced by a short, documented QuTiP~\cite{johansson2012, johansson2013} script that runs in seconds to a minute on a laptop, and the scripts are the intended instrument: the reader is meant to change $\bar{n}$, $\kappa/g$ or the initial field state and watch the figures respond. Section~\ref{sec:teaching} collects exercises built on that premise.

Our contribution relative to textbook treatments~\cite{gerry2004, haroche2006} is threefold. We compute the time-resolved Wigner function of the cavity field and quantify its non-classicality by the negativity volume; we compare the entanglement dynamics across coherent, thermal, squeezed-vacuum and Fock initial fields, using the reduced entropy where the global state is pure and the logarithmic negativity where it is mixed, so that the limits of the entropy as an entanglement measure become visible; and we quantify how cavity dissipation destroys the cat state. The pedagogical core is a three-regime picture: an entangled two-branch mixture during the collapse, a disentangled and nearly pure cat state at half the revival time, and re-entanglement at the revival.

The paper is organized as follows. Section~\ref{sec:theory} reviews the quantum states of light, the Wigner function, the JC Hamiltonian and its dressed states, and the collapse and revival timescales. Section~\ref{sec:methods} describes the computational methods, including the convergence checks that a student should reproduce. Section~\ref{sec:results} presents the simulation results. Section~\ref{sec:criteria} summarizes the criteria that distinguish classical from quantum light. Section~\ref{sec:experiment} maps the dimensionless results onto the platforms on which the phenomena have been observed. Section~\ref{sec:teaching} suggests how the material and the code can be used in a course, and Section~\ref{sec:conclusions} concludes.
"""
replace_span('While the JC model is a textbook topic', '\n\\section{Theoretical Framework}', INTRO + '\n')

# ---------------------------------------------------------------- Sec. 2.1 compressed
SEC21 = r"""\subsection{Quantum harmonic oscillator and field quantization}
\label{sec:quantization}

Each mode of the electromagnetic field is a quantum harmonic oscillator. Writing the mode Hamiltonian as $H = \hbar\omega(a^\dagger a + \tfrac{1}{2})$ with $[a, a^\dagger] = 1$, the number operator $\hat{n} = a^\dagger a$ has the Fock states $|n\rangle$ as eigenstates, with $a^\dagger|n\rangle = \sqrt{n+1}\,|n+1\rangle$ and $a|n\rangle = \sqrt{n}\,|n-1\rangle$, and the single-mode electric field operator is $\hat{E}(t) = i\mathcal{E}_0\,(a e^{-i\omega t} - a^\dagger e^{i\omega t})$, where $\mathcal{E}_0 = \sqrt{\hbar\omega/(2\varepsilon_0 V)}$ is the field amplitude of one photon in the quantization volume $V$. The ground state carries the zero-point energy $\tfrac{1}{2}\hbar\omega$. The factor $\sqrt{n+1}$ in the action of $a^\dagger$ is the origin of every $\sqrt{n+1}$ that appears below, and the reader may wish to keep it in mind. Standard derivations are given in Refs.~\cite{scully1997, gerry2004}.


"""
replace_span('\\subsection{Quantum harmonic oscillator and field quantization}', '\\subsection{Quantum states of light}', SEC21)
for lab in ('eq:ladder', 'eq:efield', 'eq:Hfield'):
    assert f'\\ref{{{lab}}}' not in s, lab

# ---------------------------------------------------------------- Sec. 2.9 removed (Mollow figure no longer shown)
replace_span('\\subsection{Dressed-state spectroscopy}', '\\subsection{Open quantum systems', '')

# ---------------------------------------------------------------- Sec. 6 condensed
SEC6 = r"""\section{Connection to Experiment}
\label{sec:experiment}

The collapse-revival phenomenon remained a theoretical prediction for over two decades after the original JC model~\cite{jaynes1963} and the analysis by Eberly \textit{et al.}~\cite{eberly1980}, because its observation requires a single two-level system coupled to a single quantized mode in the strong-coupling regime $g \gg \kappa, \gamma$. It has since been seen on four platforms. Rempe, Walther, and Klein~\cite{rempe1987} observed the first quantum revivals with Rydberg atoms crossing a superconducting microwave cavity one at a time; the same platform later yielded the generation and detection of cat states~\cite{brune1996} and quantum non-demolition counting of photons~\cite{haroche2006}, with $g/2\pi \sim 50$~kHz and $\kappa/2\pi \sim 1$~Hz. Meekhof \textit{et al.}~\cite{meekhof1996} reproduced the full collapse-revival sequence with a single trapped $^9$Be$^+$ ion whose vibrational mode plays the role of the cavity field, demonstrating that the physics belongs to any two-level system coupled to a quantized boson mode. In optical cavities, Thompson, Rempe, and Kimble~\cite{thompson1992} resolved the vacuum Rabi splitting of a single cesium atom, confirming the $n = 1$ dressed-state structure, although short optical cavity lifetimes make time-domain revivals difficult. In circuit QED~\cite{blais2021}, superconducting qubits coupled to microwave resonators with $g/2\pi \sim 100$--$300$~MHz and $\kappa/2\pi \sim 1$~MHz reach $g/\kappa \sim 100$--$300$; Hofheinz \textit{et al.}~\cite{hofheinz2009} verified the $\sqrt{n+1}$ scaling of the Rabi frequency with synthesized Fock states, and Ofek \textit{et al.}~\cite{ofek2016} used cat states in a superconducting cavity for quantum error correction beyond the break-even point.

Our dimensionless results map onto these platforms by inserting the physical value of $g$. For the microwave cavity QED parameters above ($g = 2\pi \times 50$~kHz) the revival time for $\bar{n} = 10$ is $t_r = 2\pi\sqrt{10}/g \approx 60~\mu$s, far shorter than the cavity lifetime $1/\kappa \approx 0.16$~s; for circuit QED it is $t_r \approx 10$--$30$~ns against $1/\kappa \approx 160$~ns. In both cases the first revival occurs well within the coherence time. The cat-state fringes, which decohere at the enhanced rate $2\kappa\bar{n}$, survive only where $\kappa/g \lesssim 0.01$--$0.03$, which is why the $g/\kappa \gtrsim 30$ threshold of Sec.~\ref{sec:decoherence} is met in the microwave and circuit-QED regimes but not in typical optical cavities.


"""
replace_span('\\section{Connection to Experiment}', '\\section{Conclusions}', SEC6)

# ---------------------------------------------------------------- new Sec. 7: teaching
TEACH = r"""\section{Using this material in teaching}
\label{sec:teaching}

This study grew out of a term project in a graduate course on quantum optics at Boston University (EC~585/777) and is organized so that it can be reused in that role.

\textit{Where it fits.} The natural place is immediately after the JC model and the collapse-revival phenomenon have been introduced, in a quantum-optics or cavity-QED course at advanced-undergraduate or first-year-graduate level, or as a case study in a computational-physics module. Prerequisites are second quantization of a single mode, density matrices and the partial trace, and a first exposure to the Lindblad equation; Section~\ref{sec:theory} supplies the rest. Three lectures cover the content: (a) collapse and revival as dephasing and rephasing of a discrete spectrum, using Figs.~\ref{fig:inversion_snapshots} and \ref{fig:entropy_nbar}; (b) the field in phase space, the cat state and its decoherence, using Figs.~\ref{fig:wigner_evolution}, \ref{fig:cat_detail} and \ref{fig:wigner_decoherence} and Table~\ref{tab:decoherence}; (c) entanglement measures and their limits, using Figs.~\ref{fig:entanglement_comparison}, \ref{fig:coherent_detail} and \ref{fig:dissipative_entropy}.

\textit{Misconceptions the figures are designed to confront.} Four statements are tempting and wrong, and each is refuted by a figure the student can regenerate. First, that the cat state forms when the atom and field are maximally entangled: Fig.~\ref{fig:coherent_detail} shows the entropy at its minimum, not its maximum, when the cat appears. Second, that a field purity of one half signals a superposition of two states: it signals a mixture, and the coherent superposition arrives only when the purity returns to 0.96 at $t_r/2$. Third, that a reduced entropy of one bit means maximal entanglement: for the thermal field of Fig.~\ref{fig:entanglement_comparison} the logarithmic negativity is only about 0.2, because the global state is mixed. Fourth, that a non-negative Wigner function implies a classical state: the squeezed vacuum has $\delta = 0$ and is nonetheless non-classical (Sec.~\ref{sec:criteria}).

\textit{Exercises.} All of the following run in seconds to a minute on a laptop with the scripts in the repository.
\begin{enumerate}
\item Change $\bar{n}$ in the Wigner-evolution script to 4, 16 and 25 and verify from the inversion that $t_r$ scales as $\sqrt{\bar{n}}$ while the collapse is complete by $t \approx 2/g$ regardless.
\item Derive the entropy period $\pi/(2g\sqrt{n+1})$ of the Fock state from Eq.~(\ref{eq:rabi_evolution}) and the symmetry $h(p) = h(1-p)$ of the binary entropy, then confirm it against panel (b) of Fig.~\ref{fig:entanglement_comparison}.
\item Reproduce Table~\ref{tab:decoherence} and extend it to $\kappa/g = 0.01$ and $0.03$; locate the decay rate at which $\delta$ falls below 0.05, and compare with the naive estimate obtained by equating the fringe-decoherence time $1/(2\kappa\bar{n})$ to the formation time $t_r/2$. Explain why the estimate is too conservative.
\item Using the closed form $P(n,t) = p(n)\cos^2(g\sqrt{n+1}\,t) + p(n-1)\sin^2(g\sqrt{n}\,t)$ for the photon-number distribution, show that $P(n, t_r/2)$ alternates with the parity of $n$, and compare the predicted parity $\langle(-1)^{\hat{n}}\rangle$ with the numerical value $-0.64$ quoted in Sec.~\ref{sec:wigner_results}.
\item Repeat the thermal-field simulation with $N_{\text{cav}} = 50$ instead of 150 and explain, from the initial $\langle n\rangle$, why the truncation must be chosen per initial state. This is the convergence check that separates a simulation from a picture.
\item (Advanced) Add a detuning $\Delta \neq 0$ to the Hamiltonian and investigate how the half-revival cat fidelity and the entropy minimum change; relate the result to the dispersive limit of Sec.~\ref{sec:limits}.
\end{enumerate}

\textit{Assessment.} A suitable project is to produce the three-observable portrait of Fig.~\ref{fig:coherent_detail} for a different initial state, for example a displaced Fock state or an initial atomic superposition, and to explain in one page where the cat forms, when the atom and field disentangle, and what the logarithmic negativity adds to the reduced entropy.


"""
i = s.index('\\section{Conclusions}'); s = s[:i] + TEACH + s[i:]

# ---------------------------------------------------------------- conclusions revised
CONCL = r"""\section{Conclusions}
\label{sec:conclusions}

We have presented a computational treatment of the Jaynes--Cummings model intended for teaching, in which the collapse and revival of Rabi oscillations, the phase-space dynamics of the cavity field, and the atom--field entanglement are followed together from reproducible code. Three lessons emerge that standard presentations leave implicit. First, the Schr\"{o}dinger cat state that forms at half the revival time, with Wigner negativity $\delta = 0.85$, purity 0.96 and cat fidelity 0.78, coincides with a \emph{minimum} of the atom--field entanglement ($S \approx 0.14$~bit): it is a nearly pure state of the field alone, whereas during the preceding collapse the atom and field are maximally entangled and the reduced field is a two-branch mixture. Second, the half-revival disentanglement first analyzed by Gea-Banacloche~\cite{gea-banacloche1990} and by Phoenix and Knight~\cite{phoenix1988, phoenix1991} is unique to the coherent field, and for a thermal field a saturated reduced entropy of one bit conceals a logarithmic negativity of only about 0.2, so that once the global state is mixed the reduced entropy must not be read as an entanglement measure. Third, cavity decay as weak as $\kappa/g = 0.02$ removes over 80\% of the Wigner negativity while leaving the residual atom--field negativity at $t_r/2$ nearly unchanged, which separates the loss of the field's internal coherence from the loss of entanglement.

The physics is classical work; what the computational route adds is that the three observables can be placed side by side at negligible cost, and that each of the misconceptions listed in Sec.~\ref{sec:teaching} becomes a figure a student can regenerate and then break by changing a parameter. The scripts extend without modification to detuned, multi-mode and ultrastrong-coupling variants of the model, and to quantum-trajectory simulations of individual measurement records.


"""
replace_span('\\section{Conclusions}', '\\ack{', CONCL)

# ---------------------------------------------------------------- drop bibliography entries that are no longer cited
cites = set(k.strip() for m in re.findall(r'\\cite\{([^}]*)\}', s) for k in m.split(','))
dropped = []
for key in re.findall(r'\\bibitem\{([^}]*)\}', s):
    if key not in cites:
        s = re.sub(r'\\bibitem\{' + re.escape(key) + r'\}[^\n]*\n', '', s); dropped.append(key)

# ---------------------------------------------------------------- checks
labels = set(re.findall(r'\\label\{([^}]*)\}', s)); refs = set(re.findall(r'\\ref\{([^}]*)\}', s))
assert refs <= labels, refs - labels
bibkeys = set(re.findall(r'\\bibitem\{([^}]*)\}', s)); assert cites <= bibkeys, cites - bibkeys
envs = re.findall(r'\\begin\{([a-zA-Z*]+)\}', s); ends = re.findall(r'\\end\{([a-zA-Z*]+)\}', s)
assert all(envs.count(k) == ends.count(k) for k in set(envs) | set(ends))
t = re.sub(r'(?<!\\)%.*', '', s).replace('\\{', '').replace('\\}', '')
assert t.count('{') == t.count('}')
P.write_text(s)
aw = len(re.sub(r'\\[a-zA-Z]+|[{}$^_]', ' ', ABSTRACT).split())
bw = len(re.sub(r'\\[a-zA-Z]+|[{}$^_]', ' ', s.split('\\end{abstract}')[1].split('\\begin{thebibliography}')[0]).split())
print(f"reframed {P.name}: abstract ~{aw} words, body ~{bw} words, dropped uncited refs {dropped}")
